name: Build and publish www.cyrusimap.org

on:
  push:
    branches: [ 'main', 'master' ]
  schedule:
    - cron: '33 * * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/cyrusimap/cyrus-docker:bookworm

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Restore previous build state
      uses: actions/cache/restore@v4
      with:
        path: /tmp/CYRUS_DOCS_BUILD_DIR
        key: 'last-cyrus-site-build'

    - name: Build test site
      run: |
        ./build-cyrus-site

    - name: Save this build state
      uses: actions/cache/save@v4
      with:
        path: /tmp/CYRUS_DOCS_BUILD_DIR
        key: 'last-cyrus-site-build'

    - name: Upload test site as an artifact
      id: test-site
      uses: actions/upload-pages-artifact@v3
      with:
        path: /tmp/CYRUS_DOCS_BUILD_DIR/cyrus-site/
  publish:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      pages: write

    steps:
    - name: Publish site
      uses: actions/deploy-pages@v4
      id: test-site

